---
title: "US Accidents Analysis Proposal"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Group Members: Eli Musgrove, Tanner Boyle, Hunter Rose, Aaron Jencks
### Links: https://public-iowadot.opendata.arcgis.com/datasets/crash-data-1/data, https://public-iowadot.opendata.arcgis.com/datasets/crash-vehicle-data/data

### Overview:
  - US accident dataset collected from 2016 to December 2019. The dataset has 49 columns and over 3 million rows. It also includes columns to indicate nearby features such as pedestrian crossing, junctions, exits, etc... It also includes the latitude and longitude of the crash, city, zip code, and weather information.
  
### Plan:
  - What type of weather has the biggest effect on accidents in general?
  - How do the causes of accidents differ between Ames and Des Moines taking population into account?
  - Which areas in Ames are the most dangerous for accidents? Des Moines?
  - How does bad weather impact accidents in Ames vs. Des Moines?
  - Which times of the year are highly correlated with accidents?